#ifndef DRAWINGTOOLSTATEENUM_H
#define DRAWINGTOOLSTATEENUM_H

enum class DrawingToolState {OFF, CREATE_POLYGON, ADD_TO_POLYGON, MEASURING_TOOL, MEASURING_TOOL_MOVE};

#endif // DRAWINGTOOLSTATEENUM_H
